### PR TITLE
added composer autoloading and deps management

### PR DESCRIPTION
**Pull request by thattomperson**
Just a concept, but it works.
you just need to add the project to https://packagist.org

if you want I can add a gulpfile that can build a phar for github releases

I will also re-add the ubuntu/fedora-deps back in
I just started work and don't have time at the moment

### CODE REVIEW

**Comment by bkanber** [comment]
_Wow!_ Thanks so much for doing this, it's awesome. I actually would love and really appreciate if you could give phar building a shot, mostly because I've got no experience with that.

I hope to catch some time this weekend to grab this and test it out, and merge in some of my other changes before promoting, but this looks great so far. Really appreciated, thanks again.

**Comment by thattomperson** [comment]
I'll have a look at how https://github.com/composer/composer does it when i get home

**Comment by thattomperson** [comment]
hey so i added the ability to make phars
you should just have to run `gulp build`

**Comment by thattomperson** [comment]
you may have to `composer install` and `npm install` first though

**Pull request closed without merging**
